# Generated by Django 5.2.3 on 2025-06-12 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 14, 37, 35, 24939, tzinfo=datetime.timezone.utc)),
        ),
    ]
